dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libfuse-dev
language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - bash tests/test_all.sh