[package]
name = "donkey-fs"
version = "0.1.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]

[dependencies]
fuse = "0.3.1"
libc = "0.2"
time = "0.1"
clap = "2.32.0"
slog = "2.2.3"
slog-term = "2.4.0"
failure = "0.1.1"
failure_derive = "0.1.1"