[package]
name = "mtdk"
version = "0.1.1"
authors = ["Yilin Chen <sticnarf@gmail.com>"]

[dependencies]
dkfs = { path = "../dkfs" }
fuse = "0.3.1"
libc = "0.2"
clap = "2.32.0"
slog = "2.2.3"
slog-term = "2.4.0"
time = "0.1"
failure = "0.1.1"
nix = "0.11.0"